#!/usr/bin/env python3
"""Render generated YouTube surface-map tables to Markdown."""
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load_map() -> dict:
    return json.loads((ROOT / "surface-map.json").read_text(encoding="utf-8"))


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |")
    return "\n".join(lines)


def render(data: dict) -> str:
    availability = data.get("availability", {})
    primitive_availability = availability.get("primitives", {})
    fallback_availability = availability.get("fallback_nodes", {})

    def availability_status(primitive_id: str) -> str:
        note = primitive_availability.get(primitive_id, {})
        return note.get("status", availability.get("default", "happy_path"))

    def availability_note(primitive_id: str) -> str:
        note = primitive_availability.get(primitive_id, {})
        return note.get("conditional_reason", "")

    receipt_requirements = ", ".join(data["execution_policy"]["receipt_required"])
    primitive_rows = [
        [
            primitive["id"],
            primitive["path_type"],
            availability_status(primitive["id"]),
            primitive["primary"],
            ", ".join(primitive.get("fallback_chain", [])),
            receipt_requirements,
            availability_note(primitive["id"]),
        ]
        for primitive in data["primitives"]
    ]
    search_rows = [
        [
            mode["id"],
            mode["path_type"],
            mode["route"],
            ", ".join(mode.get("required", [])),
        ]
        for mode in data["search"]["surface_modes"]
    ]
    channel_rows = [
        [
            tab["id"],
            tab["primitive_id"],
            ", ".join(tab.get("expected_renderers", [])),
        ]
        for tab in data.get("channel", {}).get("tabs", [])
    ]
    fallback_rows = [
        [name, ", ".join(chain)]
        for name, chain in sorted(data["fallback_dags"].items())
    ]
    availability_rows = [
        [item_id, note["status"], note.get("conditional_reason", "")]
        for item_id, note in sorted({**primitive_availability, **fallback_availability}.items())
    ]
    return "\n\n".join([
        "# Generated YouTube Surface Tables",
        "Generated from `surface-map.json`. Do not edit this file by hand.",
        f"Primitive count: {len(data['primitives'])}",
        "## Primitives",
        markdown_table(["Primitive", "Path", "Availability", "Primary", "Fallbacks", "Receipt Requirements", "Notes"], primitive_rows),
        "## Search Surface Modes",
        markdown_table(["Mode", "Path", "Route", "Required"], search_rows),
        "## Channel Tabs",
        markdown_table(["Tab", "Primitive", "Expected Renderers"], channel_rows),
        "## Conditional And Degraded Boundaries",
        markdown_table(["ID", "Status", "Reason"], availability_rows),
        "## Fallback DAGs",
        markdown_table(["Capability", "Chain"], fallback_rows),
    ]) + "\n"


def main() -> int:
    data = load_map()
    (ROOT / "generated-surfaces.md").write_text(render(data), encoding="utf-8")
    print("wrote agent-workspace/domain-skills/youtube/generated-surfaces.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
