#!/usr/bin/env python3
"""Render generated YouTube surface-map tables to Markdown."""
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load_map() -> dict:
    return json.loads((ROOT / "surface-map.json").read_text(encoding="utf-8"))


def markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |")
    return "\n".join(lines)


def as_dict(value: object) -> dict:
    return value if isinstance(value, dict) else {}


def as_list(value: object) -> list:
    return value if isinstance(value, list) else []


def join_list(value: object) -> str:
    return ", ".join(str(item) for item in value) if isinstance(value, list) else ""


def render(data: dict) -> str:
    availability = as_dict(data.get("availability", {}))
    primitive_availability = as_dict(availability.get("primitives", {}))
    fallback_availability = as_dict(availability.get("fallback_nodes", {}))

    def availability_status(primitive_id: str) -> str:
        note = as_dict(primitive_availability.get(primitive_id, {}))
        return note.get("status", availability.get("default", "happy_path"))

    def availability_note(primitive_id: str) -> str:
        note = as_dict(primitive_availability.get(primitive_id, {}))
        return note.get("conditional_reason", "")

    receipt_requirements = join_list(as_dict(data.get("execution_policy", {})).get("receipt_required"))
    primitive_rows = [
        [
            str(primitive.get("id", "")),
            str(primitive.get("path_type", "")),
            availability_status(str(primitive.get("id", ""))),
            str(primitive.get("primary", "")),
            join_list(primitive.get("fallback_chain")),
            receipt_requirements,
            availability_note(str(primitive.get("id", ""))),
        ]
        for primitive in as_list(data.get("primitives"))
        if isinstance(primitive, dict)
    ]
    search_rows = [
        [
            str(mode.get("id", "")),
            str(mode.get("path_type", "")),
            str(mode.get("route", "")),
            join_list(mode.get("required")),
        ]
        for mode in as_list(as_dict(data.get("search", {})).get("surface_modes"))
        if isinstance(mode, dict)
    ]
    channel_rows = [
        [
            str(tab.get("id", "")),
            str(tab.get("primitive_id", "")),
            join_list(tab.get("expected_renderers")),
        ]
        for tab in as_list(as_dict(data.get("channel", {})).get("tabs"))
        if isinstance(tab, dict)
    ]
    fallback_rows = [
        [str(name), join_list(chain)]
        for name, chain in sorted(as_dict(data.get("fallback_dags")).items())
    ]
    availability_rows = [
        [str(item_id), str(note.get("status", "")), str(note.get("conditional_reason", ""))]
        for item_id, note in sorted({**primitive_availability, **fallback_availability}.items())
        if isinstance(note, dict)
    ]
    return "\n\n".join([
        "# Generated YouTube Surface Tables",
        "Generated from `surface-map.json`. Do not edit this file by hand.",
        f"Primitive count: {len(as_list(data.get('primitives')))}",
        "## Primitives",
        markdown_table(["Primitive", "Path", "Availability", "Primary", "Fallbacks", "Receipt Requirements", "Notes"], primitive_rows),
        "## Search Surface Modes",
        markdown_table(["Mode", "Path", "Route", "Required"], search_rows),
        "## Channel Tabs",
        markdown_table(["Tab", "Primitive", "Expected Renderers"], channel_rows),
        "## Conditional And Degraded Boundaries",
        markdown_table(["ID", "Status", "Reason"], availability_rows),
        "## Fallback DAGs",
        markdown_table(["Capability", "Chain"], fallback_rows),
    ]) + "\n"


def main() -> int:
    data = load_map()
    (ROOT / "generated-surfaces.md").write_text(render(data), encoding="utf-8")
    print("wrote domain-skills/youtube/generated-surfaces.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
